# Site and SEO settings
title: Salucro Healthcare Solutions
description: The Salucro platform brings cohesive payment experiences to healthcare providers, patients, and third-party collection agencies.
email: info@salucro.com
author: Salucro
url: https://www.salucro.com
twitter:
  twitter:username: Salucro
logo: /img/general/salucroLogoBlack.svg

# Build settings
permalink: :year/:month/:title
sass:
  sass_dir: css

# plugins
plugins: 
  - jekyll-paginate
  - jekyll-seo-tag
paginate: 6
paginate_path: "/blog/page:num/"